name: flutter_challenge
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.2.0
  retrofit: ^4.1.0
  hooks_riverpod: ^2.0.0
  auto_route: ^6.0.0
  connectivity_plus: ^6.0.3
  internet_connection_checker: ^1.0.0+1
  cached_network_image: ^3.2.3
  flutter_hooks: ^0.18.4
  cupertino_icons: ^1.0.6
  pretty_dio_logger: ^1.2.0
  json_annotation: ^4.9.0
  gap: ^3.0.1
  intl: ^0.19.0
  flutter_gen: ^5.5.0+1
  photo_view: ^0.15.0
  flutter_svg: ^2.0.10+1
  shimmer: ^3.0.0
  timeago: ^3.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  json_serializable: ^6.6.2
  retrofit_generator: ^6.0.0
  auto_route_generator: ^6.0.0
  flutter_lints: ^2.0.1
  analyzer: ^5.13.0
  flutter_gen_runner: ^5.5.0+1

flutter_gen:
  integrations:
    flutter_svg: true  

flutter:
  generate: true
  uses-material-design: true
  
  assets:
    - assets/
    - assets/png/
    - assets/fonts/
    - assets/svg/

    
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf